---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: clusters-configs
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: infrastructure-buildout
  name: infrastructure-buildout
  namespace: acm-clusters-configs
spec:
  channel: acm-infrastructure-buildout/acm-gitops-pub
  placement:
    #local: true
    placementRef:
      kind: PlacementRule
      name: infrastructure-buildout